### ISSUE TITLE
Initiative roller

### ISSUE THREAD

**Issue by Matjaza** [neovatar/roll20-character-sheets#1]
First off: wow. That is a really, really nice 13th Age sheet. I was considering trying to build my own to account for a few of the things that I thought would be helpful to add to the old sheet, like the ability to track uses of spells/powers/magic items, AC/PD/MD that automatically leveled up...then I saw yours, and it already accounts for those. O_O So...that saves me some work!

Love that you've even got an NPC tab so they can have their own sheet type.

I did notice one thing I think isn't quite working properly...the initiative roller. It appears that the value it records as a result and sends to the tracker is just the die roll--it fails to actually add the modifiers and such.

The formula in the roller shows up as:

Rolling 1d20+[[floor((8+0)/2)-5+5+0

It looks like it's trying to treat just the stuff from the dex modifier on as an inline roll, but doesn't have the closing brackets.

As another small note...I'm not sure this would cause any problems in the future, but I wanted to suggest maybe encasing the MOD formulas for each stat in parentheses so they are mathematically separated from the macros they are included in.

That is: (floor((@{STR-base}+@{STR-misc})/2)-5) for instance.

This serves a couple purposes: first, it calls out more clearly in code that this is all one formula when you see it on the die tooltip (so no one gets confused about that ending -5 being a temporary modifier or something) and second, it ensures that there's no way the elements of this code get modified by elements of other code before the operation is completed. I don't think it's likely in this case, because of order of operations, but I think it might be better to cover bases.

**Comment by neovatar** [comment]
First: I am glad you like the sheet and that somebody besides me is using it!

Thanks for spotting the initiative mistake. It is fixed and I also added the parentheses to the ability mods, it really makes the roll20 formula "hover" easier to read. Good idea!
