### ISSUE TITLE
Suggestions - Magic Item bonuses / Temporary adjustments

### ISSUE THREAD

**Issue by Matjaza** [neovatar/roll20-character-sheets#2]
I really love that the sheet can now level up AC/PD/MD and the like--it's great to see that I won't have to remember to do that!

One thing I'd like to see, though, if possible: allowance for magic item bonuses and temporary bonuses  to AC/PD/MD.

I think it could work by just putting in a couple extra boxes underneath the AC/PD/MD section for each column: one for "Magic Item Bonus" and one for "Temporary Bonus."

So, and forgive me for not having a clue about tables and doing it that way, it might be like this:

![image](https://cloud.githubusercontent.com/assets/10786754/5988567/eb5ffede-a933-11e4-9ed2-365796747ce3.png)

With total being the addition of Base AC, Level, the appropriate median stat mod, Magic Item bonus, and Temporary Bonus. (Level and stat mod not shown above as they'd be pulled from elsewhere on the sheet. The above used a level 5 character with 0 median stat.)

The arrangement works vertically in the example above, but could just as easily go horizontally if you preferred. Vertically I figured the Total on top would work well to make it the most prominent on the sheet for reference.

This seems like it would be generally useful and not add too much to the sheet.

As a side note...it might be good to also have slots for magic weapon / temp bonuses to melee attacks, ranged attacks, and magic spells. I do see the +misc by the basic attacks, but it'd be cool to have a slot labeled specifically for magic bonuses that could be easily (and understandably) referenced by any macro. I guess you can use the misc slots for that, but I picture those more for random things that come up rather than roughly permanent bonuses.

**Comment by Matjaza** [comment]
(one side note that I didn't see until now--looks like the MD total does go to the right place, I think, but the tooltip reads AC rather than MD.)

**Comment by neovatar** [comment]
I added item bonus fields to abilities, basic attacks, defenses and initiative.
